# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en

early_access: false

reviews:
  profile: chill
  high_level_summary: true
  review_status: true
  review_details: false
  request_changes_workflow: false
  poem: false
  collapse_walkthrough: false
  changed_files_summary: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - developer

chat:
  auto_reply: true
