export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  Home: undefined;
  Settings: undefined;
  Account: undefined;
  EditProfile: undefined;
  ChangePassword: undefined;
  DeleteAccount: undefined;
  AppearanceScreen: undefined;
  NotificationPreferencesScreen: undefined;
  PrivacyControlsScreen: undefined;
  HelpSupportScreen: undefined;
  CommunityScreen: undefined;
  EmailScreen: undefined;
  ChatScreen: undefined;
  AppFeatures: undefined;
  OperateScreen: undefined;
  ProductIntro: undefined;
  UserGuide: undefined;
  Logout: undefined;
  ContactSupportScreen: undefined;
  };
